config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'users/index'

  resources :sponsorships do
    resources :applications
    resources :rewards, only: [:create, :destroy]
  end

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'sponsorships#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:edit, :update, :index, :show]

  root 'welcome#index'

end

app/models/application.rb
class Application < ActiveRecord::Base

belongs_to :user
belongs_to :sponsorship
has_many :rewards, through: :sponsorship

# validates :name, :length => { :minimum => 2 }
# validates :sport, :length => { :minimum => 2 }
# validates :rank, presence: true
# validates :description, :length => { :minimum => 2 }
# validates :playing_at, :length => { :minimum => 2 }
# validates :looking_for, :length => { :minimum => 2 }
# validates :level, presence: true
# validates :best_result, :length => { :minimum => 2 }
# validates :age, presence: true
# validates :location, :length => { :minimum => 2 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end


  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :first_name
   devise_parameter_sanitizer.for(:sign_up) << :last_name
   devise_parameter_sanitizer.for(:sign_up) << :admin
   devise_parameter_sanitizer.for(:sign_up) << :avatar
   devise_parameter_sanitizer.for(:sign_up) << :email
  end


end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  respond_to :html, :xml, :json

  before_action :set_application, only: [:show, :edit, :update, :destroy]
  #Requires Being Signed in to View the Following
  before_action :authenticate_user!, except:[:index, :show]
  #Enables CanCan's User settings
  before_action :get_sponsorship
  load_and_authorize_resource

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])
  end

  # GET /applications/new
  def new
    # @application = Application.new
    # respond_with(@application)
    @application = current_user.applications.build
  end

  # GET /applications/1/edit
  def edit
    @application = @sponsorship.applications.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    # @application = Application.create(application_params)

    @application = current_user.applications.build(application_params)
    @application.sponsorship_id = @sponsorship.id
    if @application.save
      redirect_to sponsorships_path, notice: 'Application created successfully'
    else
      render 'user/application'
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    @application = @sponsorship.applications.find(params[:id])
    if @application.update_attributes(application_params)
      respond_to do |format|
      format.html { redirect_to sponsorship_applications_path, notice: "Application was successfully Sponsi'd" }
    end
    else
      render 'edit'
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to sponsorship_applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def get_sponsorship
      @sponsorship = Sponsorship.find(params[:sponsorship_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name, :sport, :rank, :approval, :description, :playing_at, :looking_for, :level, :best_result, :age, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<div class="jumbotron sponsorship-form">
<%= form_for(sponsorship_application_path(@application.sponsorship_id, @application.id)) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsorship.application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @sponsorship.application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sport %><br>
    <%= f.text_field :sport %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :approval %><br>
    <%= f.radio_button(:approval, true) %>
    <%= label_tag(:approval_true, "Give Player Sponsorship") %>
    <%= f.radio_button(:approval, false) %>
    <%= label_tag(:approval_false, "Remove Sponsorship") %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/applications/edit.html.erb
<div class="container">

<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', sponsorship_application_path(@application.sponsorship_id, @application.id), class: 'btn btn-primary' %>
<%= link_to 'Back', sponsorship_applications_path(@sponsorship.id), class: 'btn btn-primary' %>

</div>

app/views/applications/index.html.erb
<% if current_user.admin == true && @sponsorship.user_id == current_user.id %>

<div class="container bg-grey">
  <!-- Title -->
  <div class="row">
      <div class="col-lg-12">
          <h3 id="pend-app">Pending Applications</h3>
      </div>
  </div>

  <hr>
  <div class="index-spons">
    <div class="row text-center">
        <% @sponsorship.applications.each do |application| %>
        <% if application.approval == false %>
        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6 hero-feature">
            <div class="thumbnail">
                <%= image_tag application.user.avatar.url(:large) %>
                <div class="caption">
                    <h3><%= application.name  %></h3>
                    <p><%= application.description %></p>
                    <p>
                        <%= link_to 'View', sponsorship_application_path(application.sponsorship_id, application.id), class:'btn btn-primary', style: 'color:#FFFFFF;' %>
                        <%= link_to 'Reject', sponsorship_application_path(application.sponsorship_id, application.id),class:'btn btn-danger', style: 'color:#FFFFFF;', method: :delete, data: { confirm: 'Are you sure?' } %>
                    </p>
                </div>
            </div>
        </div>
        <%else%>
        <h4 class="text-center">No pending applications</h4>
        <% end %>
        <%end%>
    </div>
</div>


<br>

<!-- Title -->
<div class="row">
    <div class="col-lg-12">
        <h3 id="pend-app">Approved Applications</h3>
    </div>
</div>

<hr>
<div class="approved-form">
<div class="row text-center">
    <% @sponsorship.applications.each do |application| %>
    <% if application.approval == true %>
    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6  hero-feature">
        <div class="thumbnail">
                <%= image_tag application.user.avatar.url(:large) %>
            <div class="caption">
                <h3><%= application.name  %></h3>
                <p><%= application.description %></p>
                <p>
                    <%= link_to 'View', sponsorship_application_path(application.sponsorship_id, application.id), class:'btn btn-primary',style: 'color:#FFFFFF;' %>
                    <%= link_to 'Reject', sponsorship_application_path(application.sponsorship_id, application.id), class:'btn btn-danger', style: 'color:#FFFFFF;', method: :delete, data: { confirm: 'Are you sure?' }%>
                </p>
            </div>
        </div>
    </div>
    <%else%>
    <h4 class="text-center">No approved applications</h4>
    <% end %>
    <% end %>
    <% end %>
</div>
</div>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>
<h1 id="app" class="col-lg-4 col-centered">Application for <%=@application.name%></h1>
<br>
<br>
<br>
<div class="app-show">
<p>
  <strong id="title-form">Name:</strong>
  <%= @application.name %>
</p>

<p class="title-form">
  <strong class="title-form">Age:</strong>
  <%= @application.age %>
</p>

<p>
  <strong class="title-form">Location:</strong>
  <%= @application.location %>
</p>

<p>
  <strong class="title-form">Sport:</strong>
  <%= @application.sport %>
</p>

<p>
  <strong class="title-form">Level:</strong>
  <%= @application.level %>
</p>

<p>
  <strong class="title-form">Rank:</strong>
  <%= @application.rank %>
</p>

<p>
  <strong class="title-form">Best Result:</strong>
  <%= @application.best_result %>
</p>

<p>
  <strong class="title-form">Plays/Trains at:</strong>
  <%= @application.playing_at %>
</p>

<p>
  <strong class="title-form">Description:</strong>
  <%= @application.description %>
</p>

<p>
  <strong class="title-form">What they are looking for:</strong>
  <%= @application.looking_for %>
</p>
</div>
<!-- Admin give sponsorship buttons -->
<% if current_user.admin == true && @application.sponsorship.user_id == current_user.id %>
<div class="container">
<div class="rewards-spons">
<h3>Rewards to be given</h3>
<% @sponsorship.rewards.each do |reward| %>

  <%= reward.good %><br/>
  <%= reward.number_of_goods %><br/>

<% end %>
</div>

<div class="container">

<% if @application.approval == false  %>
  <%= form_for ([@sponsorship, @application]) do |f| %>
  <%= f.hidden_field :approval, value: true %>
  <div class="actions">
    <%= f.submit "Sponsor Player", class:" btn btn-success btn-block", data: {disable_with: "Submitting..."} %>
  </div>
  <% end %>
  <% end %>
  <br>

<%= link_to 'Back', sponsorship_applications_path, class: 'btn btn-primary' %>  <%= link_to 'Reject', sponsorship_application_path(@sponsorship.id, @application.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

<br>



<br>

  <% if @application.approval == true %>
  <%= form_for ([@sponsorship, @application]) do |f| %>
  <%= f.hidden_field :approval, value: false %>
  <div class="actions">
    <%= f.submit "Remove sponsorship", class:"submit-button btn btn-warning", data: {disable_with: "Submitting..."} %>
  </div>
  <% end %>
  <% end %>


</div>

<% end  %>

<% if current_user.admin == false && current_user.id == @application.user.id %>
<%= link_to 'View Sponsponsorship', sponsorship_path(@sponsorship.id), class:" btn btn-success col-xs-6 col-xs-offset-3" %> <br> <br>
<%= link_to 'Delete Application', sponsorship_application_path(@sponsorship.id, @application.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger col-xs-6 col-xs-offset-3' %>
<% end %>