config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'users/index'

  resources :sponsorships do
    resources :applications
    resources :rewards, only: [:create, :destroy]
  end

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'sponsorships#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:edit, :update, :index, :show]

  root 'welcome#index'

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :sponsorship
  belongs_to :application


end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_filter :load_sponsorship

  def create
    # @sponsorship = Sponsorship.find(params[:sponsorship_id])
    @reward = @sponsorship.rewards.build(reward_params)
  end

  def destroy
    # @sponsorship = Sponsorship.find(params[:sponsorship_id])
    @reward = @sponsorship.rewards.find(params[:id])
    @reward.destroy
    redirect_to sponsorship_path(@sponsorship), notice: 'Review was deleted'
  end

  # def update
  #   @reward = @sponsorship.reward(params[:id])
  #   if @reward.update_attributes(reward_params)
  #     respond_with(@sponsorshop)
  #   else
  #     render 'edit'
  #   end
  # end

  private

    def reward_params
      params.require(:reward).permit(:number_of_goods, :good, :sponsorship_id)
    end

    def load_sponsorship
      @sponsorship = Sponsorship.find(params[:sponsorship_id])
    end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number_of_goods %><br>
    <%= f.number_field :number_of_goods %>
  </div>
  <div class="field">
    <%= f.label :good %><br>
    <%= f.text_field :good, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :sponsorship_id %><br>
    <%= f.text_field :sponsorship_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<h1>Listing rewards</h1>

<table>
  <thead>
    <tr>
      <th>Number of goods</th>
      <th>Good</th>
      <th>Sponsorship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= reward.number_of_goods %></td>
        <td><%= reward.good %></td>
        <td><%= reward.sponsorship_id %></td>
        <td><%= link_to 'Show', reward %></td>
        <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
        <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number of goods:</strong>
  <%= @reward.number_of_goods %>
</p>

<p>
  <strong>Good:</strong>
  <%= @reward.good %>
</p>

<p>
  <strong>Sponsorship:</strong>
  <%= @reward.sponsorship_id %>
</p>

<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>