config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'users/index'

  resources :sponsorships do
    resources :applications
    resources :rewards, only: [:create, :destroy]
  end

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'sponsorships#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:edit, :update, :index, :show]

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :applications
  has_many :rewards, through: :applications
  has_many :sponsorships #Admin

  has_attached_file :avatar, :styles => { :large => "800x500", :medium => "300x300>", :thumb => "150x150#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  protected
  def confirmation_required?
    false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        # Sends email to user when user is created.
        UserMailer.user_email(@user).deliver

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :admin, :avatar)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="jumbotron sponsorship-form">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">

    <%= f.text_field :first_name, :class => "form-control", :placeholder => "First Name" %>
  </div>

<% if @user.admin == false %>
  <div class="form-group">

    <%= f.text_field :last_name, :class => "form-control", :placeholder => "Last Name" %>
  </div>
<% end %>

  <div class="form-group">

    <%= f.email_field :email, :class => "form-control", :placeholder => "Email", autofocus: true %>
  </div>

  <div class="form-group">
    <span id="logo-color"><%= f.label "Athlete Pic" %></span><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-group">

    <% if @validatable %>
    <span id="pass-length"><em>(<%= @minimum_password_length %> characters minimum)</em></span>
    <% end %><br />
    <%= f.password_field :password, :class => "form-control", :placeholder => "Password", autocomplete: "off" %>
  </div>

  <div class="form-group">

    <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "Password confirmation", autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit class:'btn btn-success', :value => "Submit" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<h1>Editing User</h1>

<%= render 'form' %>

</div>
<%= link_to 'Show', @user, class: 'btn btn-default' %>
<%= link_to 'Back', @user, class: 'btn btn-default' %>

app/views/users/index.html.erb
<div class="container">
<div class="users-index">
<h1 id="athlete-title">Athletes</h1>

<div class="row text-center">
    <% @users.each do |user| %>

      <% if current_user && user.admin == false %>
    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 hero-feature">
                <div class="thumbnail">
                  <%= image_tag user.avatar.url(:large) %>

                    <div class="caption">
                        <h3><%= user.first_name%></h3>
                        <p><%= user.last_name %></p>
                        <p>
                            <%= link_to 'Show', user_path(user), class:'btn btn-primary', style: 'color:#FFFFFF;' %>
                        </p>
                    </div>
                </div>
            </div>
      <% end %>
  <%end%>


</div>

<h1 id="company-title">Companies</h1>



  <div class="row text-center">
      <% @users.each do |user| %>
        <% if current_user && user.admin == true%>
      <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 hero-feature">
                  <div class="thumbnail">
                    <%= image_tag user.avatar.url(:large) %>

                      <div class="caption">
                          <h3><%= user.first_name%></h3>
                          <p><%= user.last_name %></p>
                          <p>
                              <%= link_to 'Show', user_path(user), class:'btn btn-primary', style: 'color:#FFFFFF;' %>
                          </p>
                      </div>
                  </div>
              </div>
        <% end %>
    <%end%>


</div>

app/views/users/show.html.erb
<div class="container">

<h1><%=@user.first_name%> <%=@user.last_name%></h1>
  <div class="user-show">

<p>
  <span class="item-field">Name:</span>
  <span class="item-name"><%= @user.first_name %> <%= @user.last_name  %></span>
</p>

<p>
  <span class="item-field">Email:</span> <span class="item-name"><%= @user.email %></span>
</p>

<p>
  <span class="item-field">Admin Status:</span>
  <span class="item-name"><%= @user.admin? %></span>
</p>


<% if @user.admin == false %>
  <% @user.applications.each do |application| %>
    <% if application.approval == true %>
      <h2><%= application.name %></h2>
		  <h3><%= application.sponsorship.sport%></h3>
		    <% application.sponsorship.rewards.each do |reward| %>
          <ul>
			       <li><%= reward.good %>: <%= reward.number_of_goods %></li>
          </ul>
	     <%end%>
	   <%end%>
  <% end %>
<% end %>


<% if @user.admin == true && @user.sponsorships.any? %>
  <h1 class="avail">Company's Avalible Sponsorships</h1>
  <% @user.sponsorships.each do |sponsorship| %>
    <h3 class="sport"><%= sponsorship.sport %>: Level <%= sponsorship.level  %></h3>
    <p><% sponsorship.description %></p>
    <h4 class="sport">Rewards</h4>
      <ul>
        <% sponsorship.rewards.each do |reward| %>
           <li class="sport" id="list-item"> <%= reward.good %>: <%= reward.number_of_goods %> </li>
        <% end %>
      </ul>


      <% end %>
        <%elsif @user.admin == false%>
        <h3>If you want to create a sponsorship, sign in as a company</h3>
        <%else%>
        No Available Sponsorships To Be Listed
<% end %>

</div>

<% if current_user.id == @user.id %>
  <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-default' %> |
<% end %>
<%= link_to 'Back', users_path, class: 'btn btn-default' %>
</div>