config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'users/index'

  resources :sponsorships do
    resources :applications
    resources :rewards, only: [:create, :destroy]
  end

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'sponsorships#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:edit, :update, :index, :show]

  root 'welcome#index'

end

app/models/sponsorship.rb
class Sponsorship < ActiveRecord::Base
  belongs_to :user #Admin
  has_many :rewards, :dependent => :destroy 
  has_many :applications

  validates_associated :rewards
  accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true

end

app/controllers/sponsorships_controller.rb
class SponsorshipsController < ApplicationController
  before_action :set_sponsorship, only: [:show, :edit, :update, :destroy]
  # before_action :get_sponsorship
  respond_to :html

  def index
    @sponsorships = if params[:search]
          Sponsorship.where("LOWER(sport) LIKE LOWER(?)", "%#{params[:search]}%")
        else
          Sponsorship.all
        end
    respond_with(@sponsorships)
  end

  def show
    @sponsorship = Sponsorship.find(params[:id])
    @application = @sponsorship.applications.build
    @current_user_sponsorships_applied_to = []
  end

  def new
    @sponsorship = Sponsorship.new
    @sponsorship.rewards.new
    # respond_with(@sponsorship)
  end

  def edit
    @sponsorship = Sponsorship.find(params[:id])
  end

  def create
    @sponsorship = current_user.sponsorships.build(sponsorship_params)
    @sponsorship.user_id = current_user.id
    if @sponsorship.save
      respond_with(@sponsorship)
    else
      render :new
    end
    # @sponsorship = Sponsorship.new(sponsorship_params)
    # if @sponsorship.save
    #   respond_with(@sponsorship)
    # else
    #   render :new
    # end
  end

  def update
    @sponsorship = Sponsorship.find(params[:id])
    if @sponsorship.update_attributes(sponsorship_params)
      respond_with(@sponsorship)
    else
      render 'edit'
    end
  end

  def destroy
    @sponsorship.destroy
    respond_with(@sponsorship)
  end

  private

  # def get_sponsorship
  #   @sponsorship = Sponsorship.find(params[:sponsorship_id])
  # end
  # Use callbacks to share common setup or constraints between actions.

    def set_sponsorship
      @sponsorship = Sponsorship.find(params[:id])
    end

    def sponsorship_params
      params.require(:sponsorship).permit(:sport, :level, :description, :user_id, rewards_attributes: [:id, :good, :number_of_goods, :_destroy])
    end
end

app/helpers/sponsorships_helper.rb
module SponsorshipsHelper
end

app/views/sponsorships/_form.html.erb
<div class="jumbotron sponsorship-form">
<%= form_for(@sponsorship) do |f| %>
<% if @sponsorship.errors.any? %>

<div id="error_explanation">
  <h2><%= pluralize(@sponsorship.errors.count, "error") %> prohibited this sponsorship from being saved:</h2>

  <ul>
    <% @sponsorship.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <br>
  <%= f.text_field :sport, :class => "form-control", :placeholder => "Sport" %>
</div>
<div class="field">
  <br>
  <%= f.number_field :level, :class => "form-control", :placeholder => "Level (press up arrow button: 1 being pro, 10 is a pickup team)" %>
</div>
<div class="field">
  <br>
  <%= f.text_area :description, :class => "form-control", :placeholder => "Describe expectations from players and what players should expect from players" %>
</div>
<br/>

<h2 id="reward-title">Rewards</h2>

<div>
  <%= link_to_add_association 'add reward', f, :rewards, class: 'btn btn-success' %>
</div>


<br/>

<div class="action">
  <%= f.submit class:'btn btn-success btn-block', :value => "Submit" %>
</div>
<% end %>
</div>

app/views/sponsorships/_reward_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <br>
    <%= f.number_field :number_of_goods, :class => "form-control", :placeholder => "Number of particular good you will supply (use arrow keys)" %>
  </div>
  <div class="field">
   	<br>
    <%= f.text_field :good, :class => "form-control", :placeholder => "Type of good you will supply" %>
  </div>

  <p><%= link_to_remove_association "remove reward", f, class:'btn btn-danger' %></p>
  
</div>
<br/>

app/views/sponsorships/edit.html.erb
<div class="container">
<h1>Editing sponsorship</h1>


<div class="jumbotron sponsorship-form">
<%= form_for(@sponsorship) do |f| %>
<% if @sponsorship.errors.any? %>

<div id="error_explanation">
  <h2><%= pluralize(@sponsorship.errors.count, "error") %> prohibited this sponsorship from being saved:</h2>

  <ul>
    <% @sponsorship.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <br>
  <%= f.text_field :sport, :class => "form-control", :placeholder => "Sport" %>
</div>
<div class="field">
  <br>
  <%= f.number_field :level, :class => "form-control", :placeholder => "Level (press up arrow button: 1 being pro, 10 is a pickup team)" %>
</div>
<div class="field">
  <br>
  <%= f.text_area :description, :class => "form-control", :placeholder => "Describe expectations from players and what players should expect from players" %>
</div>
<br/>

<h2 id="reward-title">Rewards</h2>

<% if @sponsorship.rewards.any?  %>
  <%= f.fields_for :rewards do |reward_fields| %>
    <%= render 'reward_fields', f: reward_fields %>
  <% end %>
<% end %>

<div>
  <%= link_to_add_association 'add reward', f, :rewards, class: 'btn btn-success' %>
</div>


<br/>

<div class="action">
  <%= f.submit class:'btn btn-success btn-block', :value => "Submit" %>
</div>
<% end %>


<br/>
<%= link_to 'Show', @sponsorship, class: 'btn btn-primary ' %>

<%= link_to 'Back', @sponsorship, class: 'btn btn-primary' %>
</div>
</div>

app/views/sponsorships/index.html.erb
<div class="container">
  <div class="row">
  <h2 id="listing-title" class="pull-left">Listing sponsorships</h2>
  </div>

  <br>

<% if current_user.admin == true %>
  <div class="new_sponsor"><%= link_to 'New Sponsorship', new_sponsorship_path, class: 'btn btn-primary col-md-6 col-md-offset-3 col-xs-12', style: 'color: #ffffff' %></div>
<% end %>

</div>

<br>



<section id="bg-gray">
<div class="container">
    <div class="row text-center">
    <% @sponsorships.each do |sponsorship| %>
      <% if current_user %>
    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 hero-feature">
                <div class="thumbnail">
                  <%= image_tag sponsorship.user.avatar.url(:large) %>
                    <div class="caption">
                        <h3><%= sponsorship.sport %></h3>
                        <p><%= sponsorship.description %></p>
                        <p>
                            <%= link_to 'Show', sponsorship_path(sponsorship), class:'btn btn-primary', style: 'color:#FFFFFF;' %>
                            <% if current_user.admin == true %>
                            <%= link_to 'Destroy', sponsorship,class:'btn btn-danger', style: 'color:#FFFFFF;', method: :delete, data: { confirm: 'Are you sure?' } %>
                            <% end %>
                        </p>
                    </div>
                </div>
            </div>
      <% end %>
  <%end%>
  </div>
  </div>
</section>

<br>






<br>

app/views/sponsorships/new.html.erb
<div class = "container">
<h1>New sponsorship</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsorships_path, class: 'btn btn-primary' %>
</div>

app/views/sponsorships/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1 class="col-md-12 col-sm-12">Sponsorship for <%=@sponsorship.user.first_name%> <%=@sponsorship.user.last_name%></h1>
<br>
<br>
<br>
<br>
<div class="show-spons">
<p>
  <strong>Sport:</strong>
  <%= @sponsorship.sport %>
</p>

<p>
  <strong>Level:</strong>
  <%= @sponsorship.level %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sponsorship.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @sponsorship.user.first_name %>
</p>

<h3 id="reward-form-title" class="col-md-12 col-sm-12">Rewards</h3>

<% @sponsorship.rewards.each do |reward| %>
<p>The approved applicant receives
  <%= reward.number_of_goods %>
  <%= reward.good %>
  </p>
<% end %>
</div>
<br/>
<!-- Link to Applications -->

<% if can?(:edit, Application) %>
<%= link_to 'Applications', sponsorship_applications_path(@sponsorship.id), class: 'btn btn-info' %>

<% end %>


<!-- Apply for Sponsorship Feilds -->

<% current_user.applications.each do |application|
   @current_user_sponsorships_applied_to.push(application.sponsorship_id)
end
 %>

<% if current_user.admin == false &&  @current_user_sponsorships_applied_to.include?(@sponsorship.id) == false %>
<br>
<br>
<div class="show-application">


<h2 id="apply-title">Apply here</h2>


<%= form_for [@sponsorship, @application] do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsorship.application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @sponsorship.application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='field'>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Applicant Name" %>
  </div>
  <div class='field'>
    <%= f.number_field :age, :class => "form-control", :placeholder => "How old is the applicant?" %>
  </div>
  <div class='field'>
    <%= f.text_field :location, :class => "form-control", :placeholder => "Where are you located?" %>
  </div>
  <div class='field'>
    <%= f.text_field :sport, :class => "form-control", :placeholder => "What sport do you play?" %>
  </div>
  <div class='field'>
    <%= f.text_field :level, :class => "form-control", :placeholder => "What level do you play your sport?" %>
  </div>
  <div class='field'>
    <%= f.number_field :rank, :class => "form-control", :placeholder => "What is your ranking?" %>
  </div>
  <div class='field'>
    <%= f.text_field :best_result, :class => "form-control", :placeholder => "What was you best result in your sport?" %>
  </div>
  <div class='field'>
    <%= f.text_field :playing_at, :class => "form-control", :placeholder => "Where do you play or train? (eg National Squash Academy)" %>
  </div>
  <div class='field'>
    <%= f.text_field :description, :class => "form-control", :placeholder => "Tell us a little about yourself!" %>
  </div>
  <div class='field'>
    <%= f.text_field :looking_for, :class => "form-control", :placeholder => "What do you want out of the sponsorship?" %>
  </div>

  <%f.hidden_field :sponsorship_id, value: @sponsorship.id%>
  <div class='actions'>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
  <% end %>
</div>
<% elsif current_user.admin == false &&  @current_user_sponsorships_applied_to.include?(@sponsorship.id) == true %>
  <% current_user.applications.each do |application|
    if application.sponsorship_id == @sponsorship.id
    %>
    <%= link_to 'View Your Application', sponsorship_application_path(application.sponsorship_id, application.id), class:" btn btn-success"%>
    <% end %>
  <% end %>

<% end %>

<br><br>

<!-- Navigation -->
<% if can?(:edit, Sponsorship) %>
<%= link_to 'Edit', edit_sponsorship_path(@sponsorship), class: 'btn btn-default' %> |
<% end %>
<%= link_to 'Back', sponsorships_path, class: 'btn btn-default' %>
</div>